name: disk_lru_cache
description: Disk lru cache for flutter.
version: 0.0.1
author: JZoom <jzoom8112@gmail.com>
homepage: https://github.com/best-flutter/disk_lru_cache

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  pedantic: ^1.8.0+1

dev_dependencies:
