name: disk_lru_cache
description: Disk cache using the LRU fetch policy implemented in pure dart.
version: 0.1.0
author: JZoom <jzoom8112@gmail.com>
homepage: https://github.com/best-flutter/disk_lru_cache

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  path: ^1.6.2
  pedantic: ^1.5.0
  synchronized: ^2.1.0+1

dev_dependencies:
  test: ^1.6.5
